window.VOCAB_DATA = {
  title:    "Scary Stories for Young Foxes",
  subtitle: "The Lilac Kingdom ~ The Paw ~ The Snow Ghost",
  brand:    "SueSooEnglish",
  theme: {
    primary:     "#36454F",
    bg:          "#232D34",
    accent:      "#FF7F00",
    button:      "#FFE9D1",
    buttonHover: "#FFD6AE"
  },
  words: [
    { word: "in one's wake", part: "idiom", meaning: "~이 지나간 자리에, ~의 뒤를 이어", example: "Mia took off across bronze hills, leaves trailing in her wake.", inflected: "in her wake" },
    { word: "stifle", part: "v.", meaning: "(감정, 소리 등을) 억누르다, 참다", example: "Uly sniffed the breeze while she stifled a whimper.", inflected: "" },
    { word: "extinguish", part: "v.", meaning: "(불·빛 등을) 끄다, 끝내다", example: "Clouds swept overhead, extinguishing the sunset.", inflected: "" },
    { word: "hovel", part: "n.", meaning: "피난처, 숨을 만한 작은 움막", example: "Over the past few weeks, they'd become experts at finding safe hovels in the forest.", inflected: "" },
    { word: "intoxicating", part: "adj.", meaning: "취하게 만드는, 매혹적인", example: "But instead she caught a smooth, intoxicating scent.", inflected: "" },
    { word: "scruff", part: "n.", meaning: "목덜미", example: "She wanted to grab Uly by the scruff and drag him up the hill.", inflected: "" },
    { word: "barrel", part: "v.", meaning: "마구 질주하다, 돌진하다", example: "The badger was barreling toward her friend, who lay at the hill's base...", inflected: "" },
    { word: "abide", part: "v.", meaning: "참다, 용납하다, 견디다", example: "\"I do not abide other male foxes in my kingdom.\"", inflected: "" },
    { word: "deformed", part: "adj.", meaning: "기형의", example: "\"The runt was born deformed.\"", inflected: "" },
    { word: "delirium", part: "n.", meaning: "정신 착란, 섬망, 망상", example: "His ear spasmed, trying to determine if the sound had been real or some sleepless delirium.", inflected: "" },
    { word: "sire", part: "v.", meaning: "(동물이) 새끼를 낳다, 아비가 되다", example: "He would kill his son, so that no one would know he could sire a kit like that.", inflected: "" },
    { word: "predicament", part: "n.", meaning: "곤경, 궁지", example: "\"It seems you've found yourself in quite the predicament,\" Wynn said, smiling.", inflected: "" },
    { word: "disembodied", part: "adj.", meaning: "육체와 분리된, 몸이 없는", example: "...they'd made her paw look exactly like the disembodied paw that had been tossed into the chasm.", inflected: "" },
    { word: "outsmart", part: "v.", meaning: "~보다 더 영리하게 행동하다, 허를 찌르다", example: "\"You outsmarted your father.\"", inflected: "" },
    { word: "caress", part: "v.", meaning: "어루만지다, 달래다", example: "Winter came and caressed the sky, gently laying the sun to sleep.", inflected: "" },
    { word: "plummet", part: "v.", meaning: "곤두박질치다, 급락하다", example: "Her hind paw plummeted through the crust, swallowing her leg.", inflected: "" },
    { word: "envelop", part: "v.", meaning: "감싸다, 뒤덮다", example: "The blizzard lashed its frozen claws across the valley, enveloping Mia and Uly in torrents of white.", inflected: "" },
    { word: "embankment", part: "n.", meaning: "둑, 제방, 경사면", example: "They scaled the roots of the collapsed pine and then crossed its snowy trunk to the opposite embankment.", inflected: "" },
    { word: "subside", part: "v.", meaning: "가라앉다, 진정되다", example: "Soon all the kits were snuggled close, shivers subsiding, eyelids drowsing...", inflected: "" },
    { word: "manageable", part: "adj.", meaning: "감당할 수 있는", example: "And that made the deep drifts and the blooms of pain and the endless snowflakes somehow manageable.", inflected: "" },
    { word: "decency", part: "n.", meaning: "예의, 품위, (상황에 따른) 친절함", example: "Maybe some creature had had the decency to crawl beneath the branches and freeze to death.", inflected: "" },
    { word: "nuzzling", part: "n./v.", meaning: "코를 비비며 달래기 / 코를 들이대다", example: "Mia jerked awake. ... She just hoped Uly got back soon... nuzzling the kits closer.", inflected: "" },
    { word: "distraction", part: "n.", meaning: "주의를 분산시키는 것, 기분 전환", example: "\"We need a distraction till Uly gets back,\" she told the kits...", inflected: "" },
    { word: "fleeting", part: "adj.", meaning: "순식간의, 잠깐 동안의", example: "All that remained was a fleeting scent, moldy and sweet.", inflected: "" },
    { word: "deranged", part: "adj.", meaning: "미친, 정상이 아닌", example: "Mr. Scratch looked more deranged than ever.", inflected: "" },
    { word: "in no condition to", part: "idiom", meaning: "~할 상태가 아닌", example: "\"No, I believe I'm in no condition to fight.\"", inflected: "" },
    { word: "nauseating", part: "adj.", meaning: "역겨운, 구역질 나는", example: "Though on him, it wasn't nauseating.", inflected: "" },
    { word: "relish", part: "v.", meaning: "즐기다, 대단히 음미하다", example: "A hunt this special has to be relished.", inflected: "" },
    { word: "convulse", part: "v.", meaning: "경련을 일으키다, 발작하다", example: "Something caught in Roa's throat, and his body convulsed.", inflected: "" },
    { word: "bolster", part: "v.", meaning: "북돋우다, 강화하다", example: "This bolstered the little one's heart.", inflected: "" }
  ]
};
