window.VOCAB_DATA = {
  title:    "Scary Stories for Young Foxes",
  subtitle: "The Six Sisters",
  brand:    "SueSooEnglish",
  theme: {
    primary:     "#36454F",
    bg:          "#232D34",
    accent:      "#FF7F00",
    button:      "#FFE9D1",
    buttonHover: "#FFD6AE"
  },
  words: [
    { word: "wobble", part: "v.", meaning: "비틀거리다, 흔들리다", example: "Uly, their only brother, listened from a dark corner, wobbling on his one good foreleg.", inflected: "" },
    { word: "scold", part: "v.", meaning: "꾸짖다, 야단치다", example: "\"Girls,\" their mother scolded. \"Clean your brother now or I'll bite your lips.\"", inflected: "" },
    { word: "grimy", part: "adj.", meaning: "때 묻은, 더러운", example: "The moment their mother's shadow vanished up the stone slope, Uly's sisters stopped cleaning, leaving his skin grimy and itchy.", inflected: "" },
    { word: "clench", part: "v.", meaning: "(이를) 악물다, (주먹을) 꽉 쥐다", example: "Uly's jaw clenched. \"There's no such thing as Mr. Scratch,\" he said...", inflected: "" },
    { word: "gnash", part: "v.", meaning: "이를 갈다, 이를 부딪치다", example: "Mr. Scratch has teeth that gnash.", inflected: "" },
    { word: "runt", part: "n.", meaning: "가장 작고 약한 새끼", example: "Gobbles all the litters' runts.", inflected: "" },
    { word: "betray", part: "v.", meaning: "배신하다, (약점을) 드러내다", example: "But his body betrayed him. \"That poem's—hic!—dumb! Hic!\"", inflected: "" },
    { word: "promptly", part: "adv.", meaning: "즉시, 지체 없이", example: "Later that night, their mom dragged dinner into the den and then promptly fell asleep.", inflected: "" },
    { word: "venture", part: "v.", meaning: "위험을 무릅쓰고 가다", example: "\"You are not to venture beyond the crack, do you understand?\"", inflected: "" },
    { word: "succulent", part: "adj.", meaning: "즙이 많은, 맛있고 연한", example: "The prairie dogs will be twice as succulent when you tear open their bellies.", inflected: "" },
    { word: "take for granted", part: "idiom", meaning: "당연하게 여기다", example: "You'll never take anything for granted.", inflected: "take anything for granted" },
    { word: "cower", part: "v.", meaning: "(겁을 먹고) 움츠러들다", example: "He cowered, waiting to see which sister would start laughing.", inflected: "" },
    { word: "suppress", part: "v.", meaning: "(감정·웃음 등을) 억누르다", example: "His mother suppressed a giggle. \"My little warrior kit.\"", inflected: "" },
    { word: "relish", part: "v.", meaning: "즐기다, 대단히 음미하다", example: "Uly ate his catch slowly, relishing every bite.", inflected: "" },
    { word: "defiant", part: "adj.", meaning: "반항적인, 도전적인", example: "Ava stared at her mother, defiant.", inflected: "" },
    { word: "writhe", part: "v.", meaning: "몸부림치다, 몸을 비틀다", example: "He rolled onto his back and writhed, scratching at his sides with both hind paws.", inflected: "" },
    { word: "obscure", part: "v.", meaning: "보이지 않게 가리다", example: "\"The winds will obscure our scent, and any hawks will be swept off their strike.\"", inflected: "" },
    { word: "grudgingly", part: "adv.", meaning: "마지못해, 억지로", example: "Ava grudgingly shut her muzzle.", inflected: "" },
    { word: "wary", part: "adj.", meaning: "경계하는, 조심하는", example: "Uly gave Ava a wary look. She smirked and took a step back.", inflected: "" },
    { word: "second-guess", part: "v.", meaning: "의심하다, 사후에 번복하다", example: "He gave his mom a determined look, then, before he could second-guess himself, bounded three times.", inflected: "" },
    { word: "slump", part: "v.", meaning: "털썩 주저앉다, 푹 쓰러지다", example: "Ava's body slumped onto the rock, paws twitching, while their mother whimpered and licked her face.", inflected: "" },
    { word: "grief-stricken", part: "adj.", meaning: "비탄에 잠긴, 큰 슬픔에 빠진", example: "Ever since Ava had died, the kits' mother had been too grief-stricken to hunt.", inflected: "" },
    { word: "perimeter", part: "n.", meaning: "주변, 주위, 둘레", example: "He padded the den's perimeter. \"Shame about Ava. She was an obedient kit.\"", inflected: "" },
    { word: "obedient", part: "adj.", meaning: "순종적인, 말을 잘 듣는", example: "\"She was an obedient kit. She followed my instructions for what to do with a crippled runt.\"", inflected: "" },
    { word: "pathetic", part: "adj.", meaning: "애처로운, 한심한", example: "\"A vixen who births something this pathetic must be the one to take care of it.\"", inflected: "" },
    { word: "abrupt", part: "adj.", meaning: "갑작스러운, 돌연한", example: "He ran until the rock came to an abrupt end.", inflected: "" }
  ]
};
