window.VOCAB_DATA = {
  title:    "Horrible Histories: Woeful Second World War",
  subtitle: "Resistance Dangers ~ Winners and Losers",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#33383D",
    bg: "#15181B",
    accent: "#7FA8C9",
    button: "#E2E5E8",
    buttonHover: "#C9CED3"
  },
  words: [
    { word: "give (oneself) away", part: "phr.v.", meaning: "정체를 드러내다", example: "There are dozens of ways you can give yourself away…", inflected: "give yourself away" },
    { word: "criminal record", part: "n.", meaning: "범죄 기록, 전과", example: "One British agent, Nigel Low, had a criminal record for stealing money from his company.", inflected: "" },
    { word: "imprison", part: "v.", meaning: "투옥하다, 가두다", example: "The Soviets also imprisoned enemies inside Poland.", inflected: "" },
    { word: "round up", part: "phr.v.", meaning: "(사람들을) 잡아들이다, 검거하다", example: "...all of the area's stamp collectors were rounded up and... stamped out.", inflected: "" },
    { word: "peasant", part: "n.", meaning: "소작농, 농민", example: "...some Germans shot any Russian peasants who could read and write.", inflected: "" },
    { word: "brutal", part: "adj.", meaning: "잔인한, 무자비한", example: "The Soviet prison officers in Latvia were utterly brutal.", inflected: "" },
    { word: "utterly", part: "adv.", meaning: "완전히, 철저히", example: "The Soviet prison officers in Latvia were utterly brutal.", inflected: "" },
    { word: "crush", part: "v.", meaning: "으스러뜨리다, 짓누르다", example: "...crushed their fingers in the doors of their cells.", inflected: "" },
    { word: "fracture", part: "v./n.", meaning: "(뼈가) 부러지다, 골절", example: "...because they wanted to cause pain, not death from a fractured skull.", inflected: "" },
    { word: "savage", part: "adj.", meaning: "잔인한, 야만적인", example: "The Soviets were as savage as their new enemies, the Nazis.", inflected: "" },
    { word: "scattered", part: "adj.", meaning: "흩어진, 여기저기 널린", example: "Another cell floor was found scattered with the eyes, ears and tongues of the dead prisoners.", inflected: "" },
    { word: "dynamite", part: "n.", meaning: "다이너마이트, 폭약", example: "Sticks of dynamite were thrown in to one cell full of women prisoners.", inflected: "" },
    { word: "wipe out", part: "phr.v.", meaning: "몰살시키다, 완전히 없애다", example: "...the Soviet jailers wiped out their prisoners in Poland with unbelievable cruelty.", inflected: "" },
    { word: "affected", part: "v./adj.", meaning: "영향을 받은", example: "...the people outside the battle zones were hardly affected by the war.", inflected: "" },
    { word: "overseas", part: "adj.", meaning: "해외의", example: "Coca Cola controlled 95 percent of the overseas soft drinks market.", inflected: "" },
    { word: "manufacture", part: "v./n.", meaning: "제조(하다)", example: "The manufacturer was sent to prison for his illegal manufacture of these killer weeds.", inflected: "" },
    { word: "racketeer", part: "n.", meaning: "암거래상, 부당 이득자", example: "People who did were known as racketeers and when they were caught in Germany they could be shot.", inflected: "" },
    { word: "investigate", part: "v.", meaning: "조사하다, 수사하다", example: "They were investigated but their case was handled by Berlin's Chief of Police.", inflected: "" },
    { word: "suspect", part: "v.", meaning: "의심하다", example: "Three Nazi Ministers were suspected of being racketeers in 1944.", inflected: "" },
    { word: "estate", part: "n.", meaning: "(넓은) 사유지, 토지", example: "This man made so much money he was able to retire to a big house with an estate in the country.", inflected: "" },
    { word: "valuables", part: "n.", meaning: "귀중품", example: "Even people caught hunting through bombed ruins to take valuables were dealt with savagely.", inflected: "" },
    { word: "slave labour", part: "n.", meaning: "노예 노동", example: "...I G Farben used slave labour.", inflected: "" },
    { word: "obsessed", part: "adj.", meaning: "집착하는, 사로잡힌", example: "At Auschwitz, Doctor Josef Mengele was obsessed by twins.", inflected: "" },
    { word: "gruesome", part: "adj.", meaning: "소름 끼치는, 섬뜩한", example: "Scientists and doctors were allowed to use prisoners for gruesome experiments with new drugs and chemicals and surgery.", inflected: "" },
    { word: "forced labour", part: "n.", meaning: "강제 노동", example: "The Nazis built a forced labour camp at Auschwitz to provide slave labour for I G Farben's artificial rubber plant.", inflected: "" },
    { word: "artificial", part: "adj.", meaning: "인공의", example: "...to provide slave labour for I G Farben's artificial rubber plant.", inflected: "" },
    { word: "sawdust", part: "n.", meaning: "톱밥", example: "The prisoners were fed thin turnip soup and bread that was full of sawdust.", inflected: "" },
    { word: "fate", part: "n.", meaning: "운명", example: "But some prisoners' fate was even worse than slavery and starvation.", inflected: "" },
    { word: "surgery", part: "n.", meaning: "수술", example: "Scientists and doctors were allowed to use prisoners for gruesome experiments with new drugs and chemicals and surgery.", inflected: "" },
    { word: "law enforcer", part: "n.", meaning: "법 집행관", example: "The law enforcers of Vienna were not amused.", inflected: "" },
    { word: "despicable", part: "adj.", meaning: "비열한, 경멸스러운", example: "...so everyone could see what happened to such despicable thieves.", inflected: "" },
    { word: "criticize", part: "v.", meaning: "비판하다", example: "One woman told the Gestapo to listen under her window while her husband criticized Hitler.", inflected: "" },
    { word: "gratitude", part: "n.", meaning: "감사, 고마움", example: "But how's this for gratitude…", inflected: "" },
    { word: "inform on", part: "phr.v.", meaning: "(누군가를) 밀고하다, 고발하다", example: "It's a dangerous game, informing on others.", inflected: "informing on" },
    { word: "prove", part: "v.", meaning: "(사실로) 판명되다, 입증되다", example: "A railway worker lied about a woman neighbour and he was proved to be lying.", inflected: "" },
    { word: "siege", part: "n.", meaning: "포위 공격", example: "He would use the ancient tactic of 'siege'.", inflected: "" },
    { word: "tactic", part: "n.", meaning: "전술, 전략", example: "He would use the ancient tactic of 'siege'.", inflected: "" },
    { word: "booby-trapped", part: "adj.", meaning: "부비트랩이 설치된", example: "Hitler decided not to waste German soldiers by entering a mined and booby-trapped city.", inflected: "" },
    { word: "starve", part: "v.", meaning: "굶주리다, 굶어 죽다", example: "...and waited for the Soviets inside to starve and freeze to death.", inflected: "" },
    { word: "cannibalism", part: "n.", meaning: "식인 풍습", example: "Cannibalism was the only way that some survived.", inflected: "" }
  ]
};
