window.VOCAB_DATA = {
  title:    "Scary Stories for Young Foxes",
  subtitle: "Creeeaaak Thump! Creeeaaak Thump! ~ The Slither Out of Darkness",
  brand:    "SueSooEnglish",
  theme: {
    primary:     "#36454F",
    bg:          "#232D34",
    accent:      "#FF7F00",
    button:      "#FFE9D1",
    buttonHover: "#FFD6AE"
  },
  words: [
    { word: "inconspicuous", part: "adj.", meaning: "이목을 끌지 않는, 눈에 띄지 않는", example: "Uly sat only a few tails into the trees, foreleg folded under his chest, trying to remain inconspicuous.", inflected: "" },
    { word: "canopy", part: "n.", meaning: "나뭇가지들이 지붕처럼 우거진 것", example: "He watched as the rocky shadow of the Great Boulder slid from one side of the canopy to the other...", inflected: "" },
    { word: "entrails", part: "n.", meaning: "내장", example: "And a sound like slopping entrails swung him around again.", inflected: "" },
    { word: "twine", part: "v.", meaning: "휘감기다, 엮이다", example: "The centipedes'll twine through your nostrils / And out your ears.", inflected: "" },
    { word: "shrouded", part: "adj.", meaning: "뒤덮인, 장막에 가려진", example: "And then the Shrouded Fox will come for you / And steal you away to the Underwood.", inflected: "" },
    { word: "devour", part: "v.", meaning: "게걸스럽게 먹다, 집어삼키다", example: "...certain he was about to be plucked up by a branchy claw and devoured by the tree with many faces.", inflected: "" },
    { word: "writhe", part: "v.", meaning: "구불구불 흘러가다, 몸부림치다", example: "Patches of golden light writhed on the forest floor.", inflected: "" },
    { word: "stalk", part: "v.", meaning: "(사냥감 등에게) 몰래 접근하다", example: "Stalk quietly until your prey flees into the open.", inflected: "" },
    { word: "coppery", part: "adj.", meaning: "구리 같은, 구리 냄새가 나는", example: "A coppery scent laced the wind, leading him to a split in a tree trunk.", inflected: "" },
    { word: "edible", part: "adj.", meaning: "먹을 수 있는, 식용의", example: "...as several other edible critters fled the area...", inflected: "" },
    { word: "dully", part: "adv.", meaning: "멍하니, 흐리멍덩하게", example: "Uly lay, head in the dirt, blinking dully.", inflected: "" },
    { word: "entice", part: "v.", meaning: "유혹하다, 유인하다", example: "...singeing his nostrils as much as it enticed them.", inflected: "" },
    { word: "intoxicating", part: "adj.", meaning: "매혹적인, 취하게 만드는", example: "But this intoxicating scent lay somewhere in between...", inflected: "" },
    { word: "spew", part: "v.", meaning: "뿜어내다, 토하다", example: "Something like a rocky trunk stuck out of the grass, spewing the delicious-smelling smoke.", inflected: "" },
    { word: "grotesque", part: "adj.", meaning: "기괴한, 터무니없는", example: "Its small, grotesque paws clutched a soft oval egg to its chest.", inflected: "" },
    { word: "menacing", part: "adj.", meaning: "위협적인", example: "He hoped it sounded menacing now.", inflected: "" },
    { word: "contagious", part: "adj.", meaning: "전염성의", example: "\"Hiccups aren't contagious!\"", inflected: "" },
    { word: "churn", part: "v.", meaning: "마구 휘돌다, 요동치다", example: "The water around Uly's island began to churn.", inflected: "" },
    { word: "pleading", part: "adj.", meaning: "애원하는, 간청하는", example: "He looked at the bird with pleading eyes.", inflected: "" },
    { word: "digest", part: "v.", meaning: "소화하다", example: "...digested in its swamp-sized belly.", inflected: "" },
    { word: "casually", part: "adv.", meaning: "태연하게, 무심코", example: "\"Don't worry,\" Mia said casually.", inflected: "" },
    { word: "clench", part: "v.", meaning: "꽉 움켜쥐다, 악물다", example: "...but the teeth clenched tighter around his paw.", inflected: "" },
    { word: "mocking", part: "adj.", meaning: "조롱하는, 비웃는", example: "He could almost hear his sisters' mocking voices bubbling from the depths.", inflected: "" },
    { word: "disposable", part: "adj.", meaning: "처분할 수 있는, 일회용의", example: "...because then she would know that his family thought he was as disposable as a gopher's toenails.", inflected: "" },
    { word: "mottled", part: "adj.", meaning: "얼룩덜룩한", example: "He saw its giant eye—mottled and yellow with a sharpened pupil...", inflected: "" },
    { word: "propel", part: "v.", meaning: "나아가게 하다, 추진하다", example: "...as he propelled himself upward.", inflected: "propelled" },
    { word: "resurface", part: "v.", meaning: "다시 떠오르다, 재부상하다", example: "She whimpered and pawstepped, waiting to see if he would resurface.", inflected: "" },
    { word: "withered", part: "adj.", meaning: "기형의, 시든, 말라 죽은", example: "It was true. Uly's withered leg was gone.", inflected: "" },
    { word: "reverie", part: "n.", meaning: "몽상, 공상", example: "Uly shook himself out of his reverie.", inflected: "" },
    { word: "respite", part: "n.", meaning: "(곤경의) 일시적 중단, 휴식", example: "\"Mia and Uly's meeting was a welcome respite from what they'd been through,\" the storyteller said.", inflected: "" }
  ]
};
