window.VOCAB_DATA = {
  title:    "Horrible Histories: Woeful Second World War",
  subtitle: "Funny Food ~ Epilogue",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#33383D",
    bg: "#15181B",
    accent: "#7FA8C9",
    button: "#E2E5E8",
    buttonHover: "#C9CED3"
  },
  words: [
    { word: "hardship", part: "n.", meaning: "고난, 어려움", example: "The German people suffered even worse hardships than the British.", inflected: "" },
    { word: "bayonet", part: "v.", meaning: "총검으로 찌르다", example: "...many who fell were bayoneted.", inflected: "" },
    { word: "commandant", part: "n.", meaning: "(수용소 등의) 지휘관", example: "Arrived at the camp and were told to wait for the camp's commandant.", inflected: "" },
    { word: "ration", part: "n.", meaning: "배급(량)", example: "Day by day the rations have grown a little less.", inflected: "" },
    { word: "disgrace", part: "n.", meaning: "수치, 망신", example: "...the thing is a disgrace.", inflected: "" },
    { word: "bloated", part: "adj.", meaning: "부풀어 오른", example: "...our stomachs are bloated from hunger and disease.", inflected: "" },
    { word: "ulcer", part: "n.", meaning: "궤양", example: "...others have raw ulcers weeping on their legs.", inflected: "" },
    { word: "smuggle", part: "v.", meaning: "밀반입하다, 밀수하다", example: "Some brave women have smuggled radio parts into the camp.", inflected: "" },
    { word: "torrential", part: "adj.", meaning: "억수같이 쏟아지는", example: "...fought in the trenches in torrential rain...", inflected: "" },
    { word: "crack", part: "v.", meaning: "(암호를) 풀다, 해독하다", example: "...the Brits got a copy of the machine and cracked thousands of top secret messages.", inflected: "" },
    { word: "hint", part: "v.", meaning: "암시하다, 넌지시 알리다", example: "Letters from the camp were destroyed if they hinted at the dreadful conditions.", inflected: "" },
    { word: "viciousness", part: "n.", meaning: "잔인함, 악랄함", example: "One thing which seemed to bring out their viciousness was revenge.", inflected: "" },
    { word: "reprisal", part: "n.", meaning: "보복", example: "They were called 'reprisals'.", inflected: "" },
    { word: "spare", part: "v.", meaning: "(해를 끼치지 않고) 봐주다", example: "...not even the women and children were spared.", inflected: "" },
    { word: "camouflage", part: "n.", meaning: "위장", example: "British and Allied troops coloured everything khaki brown as camouflage.", inflected: "" },
    { word: "deserter", part: "n.", meaning: "탈영병", example: "The USA shot only one of their 19,000 deserters in the whole of the war.", inflected: "" },
    { word: "mercy killing", part: "n.", meaning: "안락사", example: "The aim of this 'mercy killing' of mentally or physically handicapped adults or children was to ensure racial purity.", inflected: "" },
    { word: "rumour", part: "n.", meaning: "소문", example: "Rumours spread and in 1941, the Roman Catholic Archbishop of Munster exposed the Nazi murders in a sermon.", inflected: "" },
    { word: "sermon", part: "n.", meaning: "설교", example: "...exposed the Nazi murders in a sermon.", inflected: "" },
    { word: "minefield", part: "n.", meaning: "지뢰밭", example: "We'd just laid a minefield in the desert to stop the German tanks advancing.", inflected: "" },
    { word: "splinter", part: "n.", meaning: "파편, 조각", example: "...a shell splinter deep in his chest.", inflected: "" },
    { word: "rampart", part: "n.", meaning: "성벽, 흉벽", example: "Behind the rampart we found a young blond-haired officer...", inflected: "" },
    { word: "weave", part: "v.", meaning: "(좌우로) 요리조리 나아가다", example: "...it started weaving slowly, left and right...", inflected: "" },
    { word: "unsinkable", part: "adj.", meaning: "가라앉지 않는", example: "Ships built of Pykrete would be unsinkable and win the war.", inflected: "" },
    { word: "churn", part: "v.", meaning: "뒤섞이다, 휘젓다", example: "...it was known for tanks to churn themselves in until only the turret remained visible.", inflected: "" },
    { word: "plundering", part: "n.", meaning: "약탈", example: "Plundering gold teeth from their Japanese enemies was another charming hobby.", inflected: "" },
    { word: "hooligan", part: "n.", meaning: "폭력배, 난동꾼", example: "...some football matches give hooligans a similar sort of excuse to break the rules.", inflected: "" },
    { word: "flimsy", part: "adj.", meaning: "허술한, 부실한", example: "When we broke down the flimsy doors to their rooms...", inflected: "" },
    { word: "hoard", part: "v.", meaning: "사재기하다, 비축하다", example: "Shopkeepers who had been jealously hoarding stocks... began selling them.", inflected: "" },
    { word: "henchman", part: "n.", meaning: "부하, 심복", example: "Hitler's henchman, Heydrich, said...", inflected: "" }
  ]
};
