window.VOCAB_DATA = {
  title:    "Silent Spring",
  subtitle: "Ch.4-5",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#2E2E2E",
    bg: "#0D0D0D",
    accent: "#B0B0B0",
    button: "#F0F0F0",
    buttonHover: "#D9D9D9"
  },
  words: [
    { word: "paradox", part: "n.", meaning: "역설, 모순", example: "By a strange paradox, most of the earth's abundant water is not usable for agriculture, industry, or human consumption.", inflected: "" },
    { word: "augment", part: "v.", meaning: "증대시키다, 키우다", example: "Many of the chemical agents in this alarming mélange imitate and augment the harmful effects of radiation.", inflected: "" },
    { word: "appalling", part: "adj.", meaning: "끔찍한, 경악스러운", example: "...an appalling deluge of chemical pollution is daily poured into the nation's waterways.", inflected: "" },
    { word: "defy", part: "v.", meaning: "무력화하다, (~을) 허용하지 않다", example: "...these chemicals sometimes defy detection by the methods in ordinary use by purification plants.", inflected: "" },
    { word: "leach", part: "v.", meaning: "(빗물에) 씻겨 나오다, 침출되다", example: "...agricultural chemicals that have been... leached out of the ground by rains...", inflected: "" },
    { word: "tributary", part: "n.", meaning: "지류", example: "...in fifteen streams tributary to the Tennessee River in Alabama...", inflected: "" },
    { word: "seepage", part: "n.", meaning: "스며 나옴, 침출", example: "This seepage had continued to spread and had further contaminated an area of unknown extent.", inflected: "" },
    { word: "spontaneously", part: "adv.", meaning: "저절로, 자연발생적으로", example: "...the chemists at the plant concluded that the 2,4-D had been formed spontaneously in the open basins.", inflected: "" },
    { word: "transcend", part: "v.", meaning: "넘어서다, 초월하다", example: "...the story of the Colorado farms and their damaged crops assumes a significance that transcends its local importance.", inflected: "" },
    { word: "innocuous", part: "adj.", meaning: "무해한, 해가 없어 보이는", example: "...the production of harmful substances from comparatively innocuous chemicals may be taking place on quite a wide scale.", inflected: "" },
    { word: "irreparable", part: "adj.", meaning: "회복할 수 없는", example: "...the damage to the waterfowl populations of the Far West could be irreparable.", inflected: "" },
    { word: "turbid", part: "adj.", meaning: "(물이) 탁한, 흐린", example: "The name is inappropriate, for actually it is a rather turbid lake.", inflected: "" },
    { word: "dilution", part: "n.", meaning: "희석", example: "...the insecticide applied in such great dilution that for every part of chemical there would be 70 million parts of water.", inflected: "" },
    { word: "resilient", part: "adj.", meaning: "회복력이 강한, 잘 되살아나는", example: "Following a third assault on the ever-resilient gnat population, in 1957, more grebes died.", inflected: "" },
    { word: "dwindle", part: "v.", meaning: "점점 줄어들다", example: "Meanwhile, the nesting colonies of the grebes dwindled—from more than 1000 pairs... to about 30 pairs in 1960.", inflected: "" },
    { word: "tangible", part: "adj.", meaning: "눈에 보이는, 실체가 있는", example: "...solution of an obvious and often trivial problem creates a far more serious but conveniently less tangible one.", inflected: "" },
    { word: "inert", part: "adj.", meaning: "활성이 없는, 생명 없는", example: "Then living things began to work their creative magic and little by little these inert materials became soil.", inflected: "" },
    { word: "disintegration", part: "n.", meaning: "붕괴, 분해", example: "Lichens, the rocks' first covering, aided the process of disintegration by their acid secretions.", inflected: "" },
    { word: "myriad", part: "adj.", meaning: "무수히 많은", example: "...the myriad organisms of the soil make it capable of supporting the earth's green mantle.", inflected: "" },
    { word: "teeming", part: "adj.", meaning: "바글바글한, 가득 찬", example: "There are few studies more fascinating... than those of the teeming populations that exist in the dark realms of the soil.", inflected: "" },
    { word: "aerate", part: "v.", meaning: "공기가 통하게 하다", example: "...their burrows aerate the soil, keep it well drained, and aid the penetration of plant roots.", inflected: "" },
    { word: "sustain", part: "v.", meaning: "견디다, 감당하다", example: "Chemical control of insects seems to have proceeded on the assumption that the soil could and would sustain any amount of insult.", inflected: "" },
    { word: "apprehension", part: "n.", meaning: "우려, 불안", example: "...enough solid evidence of harm is accumulating to cause apprehension on the part of many scientists.", inflected: "" },
    { word: "detrimental", part: "adj.", meaning: "해로운", example: "...BHC and DDT had significantly detrimental effects a year after treatment.", inflected: "" },
    { word: "disrupt", part: "v.", meaning: "무너뜨리다, 방해하다", example: "A curious but beneficial relation between fungi and the roots of higher plants is seriously disrupted.", inflected: "" },
    { word: "impregnate", part: "v.", meaning: "배어들게 하다, 스며들게 하다", example: "...the soils of tobacco plantations are now thoroughly impregnated with residues of a heavy and relatively insoluble poison.", inflected: "" },
    { word: "insoluble", part: "adj.", meaning: "녹지 않는, 용해되지 않는", example: "...a heavy and relatively insoluble poison, arsenate of lead.", inflected: "" },
    { word: "telltale", part: "adj.", meaning: "숨길 수 없이 드러나는", example: "Actually, only a trace is enough to incorporate the telltale musty odor and taste.", inflected: "" },
    { word: "accentuate", part: "v.", meaning: "더 두드러지게 하다", example: "Processing, far from removing the mustiness, sometimes accentuates it.", inflected: "" },
    { word: "anomalous", part: "adj.", meaning: "이례적인, 앞뒤가 맞지 않는", example: "The federal Department of Agriculture... found itself in the anomalous position of declaring heptachlor to be acceptable for use on hops.", inflected: "" }
  ]
};
