window.VOCAB_DATA = {
  title:    "Tales of a Fourth Grade Nothing",
  subtitle: "Ch.1-2",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#6F4E37",
    bg: "#2B1B12",
    accent: "#C68B59",
    button: "#F0DCC8",
    buttonHover: "#E3C6A8"
  },
  words: [
    { word: "announced", part: "v.", meaning: "발표했다, 선언했다", example: "\"Peter Warren Hatcher is the big winner!\" Mrs. Fargo announced.", inflected: "" },
    { word: "cushioned", part: "adj.", meaning: "쿠션이 있는, 푹신한", example: "There's a soft, cushioned bench to sit on...", inflected: "" },
    { word: "operator", part: "n.", meaning: "(엘리베이터) 운전사, 기사", example: "The elevator operator's name is Henry Bevelheimer.", inflected: "" },
    { word: "made a face", part: "idiom", meaning: "얼굴을 찡그렸다", example: "My mother made a face. \"I don't like the way he smells,\" she said.", inflected: "" },
    { word: "supposed to", part: "phr.", meaning: "~하기로 되어 있다, 당연히 ~하다", example: "Well, he's supposed to. That's what he is!", inflected: "" },
    { word: "see to it that", part: "phr.", meaning: "반드시 ~하도록 하다, 꼭 챙기다", example: "I'm going to see to it that he's happy!", inflected: "" },
    { word: "groan", part: "n.", meaning: "끙 하는 소리, 신음", example: "This time my mother made a funny noise. Like a groan.", inflected: "" },
    { word: "scrub", part: "v.", meaning: "(비누로) 문질러 씻다", example: "Peter, go and scrub your hands!", inflected: "" },
    { word: "advertising", part: "n.", meaning: "광고업", example: "That's because he's in the advertising business.", inflected: "" },
    { word: "commercials", part: "n.", meaning: "(TV, 라디오) 광고", example: "He spends a lot of time watching commercials on TV.", inflected: "" },
    { word: "crate", part: "n.", meaning: "(운반용) 상자", example: "...he sent my father a whole crate of Juicy-O...", inflected: "" },
    { word: "combination", part: "n.", meaning: "조합, 결합", example: "It tastes like a combination of oranges, pineapples, grapefruits...", inflected: "" },
    { word: "getting sick of", part: "idiom", meaning: "~에 질리고 있다, 넌더리가 나다", example: "I'm getting pretty sick of drinking it.", inflected: "getting pretty sick of" },
    { word: "none of my business", part: "idiom", meaning: "내가 상관할 일이 아니다", example: "It's none of my business.", inflected: "" },
    { word: "slurping", part: "adj./n.", meaning: "후루룩거리는 (소리)", example: "...and makes a slurping noise.", inflected: "" },
    { word: "hide-a-bed", part: "n.", meaning: "소파 겸용 침대 (소파가 밤에 침대로 펴지는 것)", example: "She put fancy sheets and a brand-new blanket on the hide-a-bed.", inflected: "" },
    { word: "den", part: "n.", meaning: "(가족용) 서재, 휴식 공간", example: "It's in Fudge's room because that used to be our den.", inflected: "" },
    { word: "cooked up a storm", part: "idiom", meaning: "(음식을) 매우 푸짐하게/열심히 요리했다", example: "She really cooked up a storm.", inflected: "" },
    { word: "racket", part: "n.", meaning: "시끄러운 소리, 소음", example: "A person can get an awful headache listening to that racket.", inflected: "" },
    { word: "measly", part: "adj.", meaning: "(양 등이) 쥐꼬리만 한, 보잘것없는", example: "What would I do with two measly flowers?", inflected: "" },
    { word: "fished out", part: "phr.v.", meaning: "(손으로) 끄집어냈다, 꺼냈다", example: "She picked him up and forced his mouth open. She fished out a rose petal.", inflected: "" },
    { word: "advantages", part: "n.", meaning: "이점, 장점", example: "Being nine has its advantages!", inflected: "" },
    { word: "cuddling", part: "v.", meaning: "껴안다, 꼭 안다", example: "She walked into the living room cuddling him.", inflected: "" },
    { word: "polite", part: "adj.", meaning: "예의 바른, 공손한", example: "But I knew I had to be polite so I said, \"Thank you...\"", inflected: "" },
    { word: "vanish", part: "v.", meaning: "(갑자기) 사라지다", example: "I wanted to vanish.", inflected: "" },
    { word: "insulted", part: "adj.", meaning: "모욕당한, 기분이 상한", example: "She sounded insulted.", inflected: "" },
    { word: "It's the thought that counts", part: "idiom", meaning: "중요한 것은 마음(성의)이다", example: "\"It's the thought that counts,\" my mother said.", inflected: "" },
    { word: "shrieked", part: "v.", meaning: "(날카롭게) 비명을 질렀다", example: "Mrs. Yarby shrieked. \"Ohhhh! I can't stand reptiles.\"", inflected: "" },
    { word: "boomed", part: "v.", meaning: "(목소리가) 쩌렁쩌렁 울렸다", example: "\"HATCHER!\" Mr. Yarby boomed.", inflected: "" },
    { word: "had a lot of nerve", part: "idiom", meaning: "정말 뻔뻔하다, 간도 크다", example: "I thought Mr. Yarby had a lot of nerve to hint that we had no manners.", inflected: "" }
  ]
};
