window.VOCAB_DATA = {
  title:    "Silent Spring",
  subtitle: "Ch.6-8",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#2E2E2E",
    bg: "#0D0D0D",
    accent: "#B0B0B0",
    button: "#F0F0F0",
    buttonHover: "#D9D9D9"
  },
  words: [
    { word: "utility", part: "n.", meaning: "유용성, 쓸모", example: "If we see any immediate utility in a plant we foster it.", inflected: "" },
    { word: "intimate", part: "adj.", meaning: "긴밀한, 밀접한", example: "The earth's vegetation is part of a web of life in which there are intimate and essential relations between plants and the earth...", inflected: "" },
    { word: "eradication", part: "n.", meaning: "근절, 뿌리뽑기", example: "Yet the program of sage eradication has been under way for a number of years.", inflected: "" },
    { word: "conjectural", part: "adj.", meaning: "추측에 불과한", example: "The eventual effects of eliminating sage and seeding with grass are largely conjectural.", inflected: "" },
    { word: "insatiable", part: "adj.", meaning: "만족을 모르는, 끝없는", example: "...the land management agencies have set about to satisfy the insatiable demands of the cattlemen for more grazing land.", inflected: "" },
    { word: "desolation", part: "n.", meaning: "황폐, 황량함", example: "Now all was brown desolation.", inflected: "" },
    { word: "desecration", part: "n.", meaning: "훼손, 모독", example: "...oases that made the desecration of the greater part of the road the more unbearable.", inflected: "" },
    { word: "perpetuate", part: "v.", meaning: "(문제를) 계속되게 하다", example: "It is perpetuating the problem it seeks to correct...", inflected: "" },
    { word: "inherent", part: "adj.", meaning: "본래 지닌, 내재된", example: "It took advantage of the inherent stability of nature...", inflected: "" },
    { word: "emulate", part: "v.", meaning: "본받다, 모방하다", example: "Where man has been intelligent enough to observe and to emulate Nature he, too, is often rewarded with success.", inflected: "" },
    { word: "boomerang", part: "v.", meaning: "역효과를 내다", example: "Ragweed... offers an interesting example of the way efforts to control nature sometimes boomerang.", inflected: "" },
    { word: "havoc", part: "n.", meaning: "큰 파괴, 대혼란", example: "...we are adding a new chapter and a new kind of havoc—the direct killing of birds, mammals, fishes...", inflected: "" },
    { word: "dilemma", part: "n.", meaning: "딜레마, 난처한 선택", example: "The citizen who wishes to make a fair judgment of the question of wildlife loss is today confronted with a dilemma.", inflected: "" },
    { word: "categorically", part: "adv.", meaning: "단정적으로, 딱 잘라", example: "...the control agencies tend to deny flatly and categorically that such losses have occurred.", inflected: "" },
    { word: "unbiased", part: "adj.", meaning: "편향되지 않은", example: "...from observers familiar with the ways of wildlife, and unbiased in favor of chemicals...", inflected: "" },
    { word: "succumb", part: "v.", meaning: "굴복하다, 쓰러져 죽다", example: "What usually results is a poisoned environment, a lethal trap in which not only the resident populations succumb...", inflected: "" },
    { word: "drastic", part: "adj.", meaning: "극단적인, 과격한", example: "Little need was shown for this drastic and dangerous action.", inflected: "" },
    { word: "allay", part: "v.", meaning: "(불안을) 가라앉히다", example: "In a somewhat mistaken attempt to allay fears, he added that the planes had emergency valves...", inflected: "" },
    { word: "annihilate", part: "v.", meaning: "전멸시키다", example: "Robins were 'almost annihilated', according to the biologists' report.", inflected: "" },
    { word: "acquiescent", part: "adj.", meaning: "순순히 따르는, 묵인하는", example: "...they would surely have been less acquiescent.", inflected: "" },
    { word: "viable", part: "adj.", meaning: "생존 가능한, 효력이 유지되는", example: "The organism remains viable in the soil for years...", inflected: "" },
    { word: "insidiously", part: "adv.", meaning: "서서히 알아채지 못하게", example: "...have come about swiftly, insidiously, and unnoticed by those whose communities are as yet unaffected.", inflected: "" },
    { word: "devoid of", part: "phr.", meaning: "~이 전혀 없는", example: "After several years of DDT spray, the town is almost devoid of robins and starlings.", inflected: "" },
    { word: "futile", part: "adj.", meaning: "헛된, 소용없는", example: "...a disease so serious that many experts believe all efforts to save the elms will in the end be futile.", inflected: "" },
    { word: "tenacious", part: "adj.", meaning: "끈질기게 들러붙는", example: "The poison forms a tenacious film over the leaves and bark.", inflected: "" },
    { word: "inadvertently", part: "adv.", meaning: "무심코, 의도치 않게", example: "Campus earthworms had been fed inadvertently to crayfish in a research project...", inflected: "" },
    { word: "sterility", part: "n.", meaning: "불임, 생식 불능", example: "The shadow of sterility lies over all the bird studies...", inflected: "" },
    { word: "mortality", part: "n.", meaning: "사망률", example: "...reported the robin mortality to be at least 86 to 88 per cent.", inflected: "" },
    { word: "vulnerable", part: "adj.", meaning: "취약한", example: "The feeding habits of all these birds not only make them especially vulnerable to insect sprays...", inflected: "" },
    { word: "resurgence", part: "n.", meaning: "재증가, 다시 들끓음", example: "When later there is a resurgence of the insect population, as almost always happens, the birds are not there to keep their numbers in check.", inflected: "" }
  ]
};
