window.VOCAB_DATA = {
  title:    "Close to Famous",
  subtitle: "Ch.26 ~ Ch.30",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#4A7C59",
    bg: "#1B2E20",
    accent: "#A8D5BA",
    button: "#E4F2E8",
    buttonHover: "#D0E8D6"
  },
  words: [
    { word: "let someone have it", part: "phr.", meaning: "~에게 퍼붓다, 한바탕 쏘아붙이다", example: "...when Mama came home, I let her have it.", inflected: "let her have it" },
    { word: "burden", part: "n.", meaning: "짐, 부담", example: "\"This is a good place to come and lay your burdens down.\"", inflected: "" },
    { word: "crumbling", part: "adj.", meaning: "무너져가는, 허물어지는", example: "\"Why does that Perseverance Wilson keep holding on to this crumbling building?\"", inflected: "" },
    { word: "tend", part: "v.", meaning: "돌보다, 가꾸다", example: "\"Is that why you keep tending the garden?\"", inflected: "" },
    { word: "bulb", part: "n.", meaning: "알뿌리, 구근", example: "\"I'm going to be planting tulip bulbs and daffodils...\"", inflected: "" },
    { word: "hoe", part: "n.", meaning: "괭이", example: "She stood up and grabbed her hoe.", inflected: "" },
    { word: "hornet's nest", part: "phr.", meaning: "벌집 (건드리면 큰일 나는 것)", example: "Opening this box was like upsetting a hornet's nest.", inflected: "" },
    { word: "tuck", part: "n./v.", meaning: "(옷의) 주름을 잡아 줄임", example: "\"...give this a tuck around your waist.\"", inflected: "" },
    { word: "heartbreaker", part: "n.", meaning: "마음을 뒤흔드는 사람", example: "\"You'll be a real heartbreaker.\"", inflected: "" },
    { word: "by the skin of one's teeth", part: "phr.", meaning: "간신히, 가까스로", example: "\"I got out of that school by the skin of my teeth.\"", inflected: "by the skin of my teeth" },
    { word: "limited", part: "adj.", meaning: "한계가 있는, 제한된", example: "I told her about being limited.", inflected: "" },
    { word: "jumble", part: "n.", meaning: "뒤죽박죽, 뒤섞인 것", example: "The words were a jumble to me.", inflected: "" },
    { word: "squiggle", part: "n.", meaning: "구불구불한 선", example: "She put a squiggle line under her name.", inflected: "" },
    { word: "on the force", part: "phr.", meaning: "경찰로 근무 중인", example: "...his cousin was on the force and he covered the whole thing up.", inflected: "" },
    { word: "cover up", part: "phr.v.", meaning: "은폐하다, 덮어버리다", example: "...his cousin...covered the whole thing up.", inflected: "" },
    { word: "God's honest truth", part: "phr.", meaning: "맹세코 사실인 것", example: "\"I can tell you, Foster, and this is God's honest truth.\"", inflected: "" },
    { word: "on the lookout for", part: "phr.", meaning: "~을 경계하며 살피다", example: "I told Macon, Garland, and Amy to be on the lookout for a yellow Cadillac.", inflected: "" },
    { word: "work release", part: "phr.", meaning: "(재소자) 외부 통근 작업", example: "\"They've got him out on this work release...\"", inflected: "" },
    { word: "divorce", part: "n.", meaning: "이혼", example: "\"I want a divorce.\"", inflected: "" },
    { word: "contract", part: "n.", meaning: "계약(서)", example: "The contract was going through.", inflected: "" },
    { word: "devastated", part: "adj.", meaning: "큰 충격을 받은, 망연자실한", example: "\"I was devastated, humiliated.\"", inflected: "" },
    { word: "humiliated", part: "adj.", meaning: "굴욕을 당한", example: "\"I was devastated, humiliated.\"", inflected: "" },
    { word: "parade", part: "v.", meaning: "과시하듯 돌아다니다", example: "\"They were parading all over the world, this happy, perfect couple.\"", inflected: "" },
    { word: "agony", part: "n.", meaning: "극심한 고통, 괴로움", example: "\"'Charleena's Agony.' That was the headline.\"", inflected: "" },
    { word: "jilted", part: "adj.", meaning: "(연인에게) 버림받은", example: "\"I was famous for being a jilted wife.\"", inflected: "" },
    { word: "betrayed", part: "adj.", meaning: "배신당한", example: "...feeling betrayed.", inflected: "" },
    { word: "voice-over", part: "n.", meaning: "(화면 밖) 내레이션, 더빙 목소리", example: "\"They want me to do the voice-over for a horse...\"", inflected: "" },
    { word: "fade in", part: "phr.", meaning: "(영화) 화면이 서서히 밝아지며 시작됨", example: "\"Fade in. It means the movie is starting...\"", inflected: "" },
    { word: "take it to the bank", part: "phr.", meaning: "확실하다, 믿어도 좋다", example: "\"...you can take it to the bank, but only ten percent of it.\"", inflected: "" },
    { word: "guff", part: "n.", meaning: "헛소리, 함부로 구는 말", example: "\"She's...not going to take any guff from anything or anybody.\"", inflected: "" },
    { word: "lose one's nerve", part: "phr.", meaning: "용기를 잃다, 겁먹다", example: "\"Well, before I lose my nerve...\"", inflected: "lose my nerve" }
  ]
};
