window.VOCAB_DATA = {
  title:    "Scary Stories for Young Foxes",
  subtitle: "House of Trix",
  brand:    "SueSooEnglish",
  theme: {
    primary:     "#36454F",
    bg:          "#232D34",
    accent:      "#FF7F00",
    button:      "#FFE9D1",
    buttonHover: "#FFD6AE"
  },
  words: [
    { word: "abrupt", part: "adj.", meaning: "갑작스러운, 돌연한", example: "...until the leaves came to an abrupt end and the world opened like a gasp.", inflected: "" },
    { word: "persist", part: "v.", meaning: "집요하게 계속하다, 지속되다", example: "The questions persisted as Mia and her mom crossed the meadow...", inflected: "" },
    { word: "bristle", part: "v.", meaning: "빽빽하다, 털을 곤두세우다", example: "The trees bristled and smelled of sap.", inflected: "" },
    { word: "knead", part: "v.", meaning: "꾹꾹 누르다, 주무르다", example: "Mia's paws kneaded the dirt.", inflected: "" },
    { word: "infestation", part: "n.", meaning: "(해충 등의) 극성, 창궐, 바글거림", example: "\"Ooh, and it has a centipede infestation!\"", inflected: "" },
    { word: "loam", part: "n.", meaning: "양토 (비옥하고 부드러운 흙)", example: "Sniff for sandy loam, a sipping creek, and an entrance with good cover.", inflected: "" },
    { word: "dense", part: "adj.", meaning: "밀집한, 빽빽한", example: "It was as tall as a sapling and seemed to be having trouble getting through the dense forest.", inflected: "" },
    { word: "deft", part: "adj.", meaning: "날래고 능숙한, 솜씨 좋은", example: "Hands. With five fingers each, every one as deft as a baby snake.", inflected: "" },
    { word: "wince", part: "v.", meaning: "움찔하다, 찌푸리다", example: "The human didn't so much as wince, only clucked its tongue.", inflected: "" },
    { word: "heft", part: "v.", meaning: "들어 올리다", example: "...and the human hefted her into the air by the scruff.", inflected: "" },
    { word: "billow", part: "v.", meaning: "(연기·구름 등이) 피어오르다", example: "Black smoke billowed from its top, hazing the air and stinging Mia's eyes.", inflected: "" },
    { word: "indignity", part: "n.", meaning: "수치, 모욕, 굴욕", example: "\"Though I won't do either of us the indignity of checking.\"", inflected: "" },
    { word: "partial to", part: "idiom", meaning: "~을 특히 좋아하는", example: "\"I'm not particularly partial to foxes,\" the woman continued.", inflected: "" },
    { word: "raise one's hackles", part: "idiom", meaning: "털을 곤두세우게 하다, 소름 돋게 하다", example: "The sound raised Mia's hackles.", inflected: "raised Mia's hackles" },
    { word: "impale", part: "v.", meaning: "꽂다, 고정시키다 (표본으로 박아두다)", example: "Mia searched the den's other walls and found that they were impaled with forest things...", inflected: "" },
    { word: "gobbledygook", part: "n.", meaning: "무슨 말인지 알 수 없는 말, 배배 꼬인 말", example: "\"It was all gobbledygook and gibberish to my ears until she stole a bit of my fur.\"", inflected: "" },
    { word: "hue", part: "n.", meaning: "빛깔, 색조", example: "...had markings that showed a bit of nature—trees and rivers and skies—all captured in watery hues.", inflected: "" },
    { word: "dim-witted", part: "adj.", meaning: "우둔한, 멍청한", example: "...and rested a forepaw on the shoulder of a dim-witted-looking duck.", inflected: "" },
    { word: "essence", part: "n.", meaning: "본질, 정수, (생명체의) 영혼/기운", example: "\"She starts by stealing your essence with her pencils.\"", inflected: "" },
    { word: "waft", part: "v.", meaning: "(퍼지는 냄새·소리 등이) 가볍게 풍기다", example: "A scent wafted through the den.", inflected: "" },
    { word: "woozy", part: "adj.", meaning: "정신이 몽롱한, 어지러운", example: "It tickled Mia's nostrils, making her head feel woozy, her eyelids heavy.", inflected: "" },
    { word: "muffled", part: "adj.", meaning: "(소리가) 낮춰진, 먹먹한", example: "The rabbit made a muffled grunting.", inflected: "" },
    { word: "dispose of", part: "idiom", meaning: "~을 처분하다, 없애다", example: "The bunny's innards disposed of, Miss Potter summoned a small waterfall...", inflected: "disposed of" },
    { word: "fidget", part: "v.", meaning: "안절부절못하다, 꼼지락거리다", example: "\"Enough fidgeting, Little Miss!\" Miss Potter said.", inflected: "" },
    { word: "inevitable", part: "adj.", meaning: "불가피한, 피할 수 없는 (the inevitable: 필연적인 일)", example: "\"Well ... no use in avoiding the inevitable.\"", inflected: "" },
    { word: "culprit", part: "n.", meaning: "범인, 장본인", example: "She searched the room for the culprit, never dreaming that Mia could have let herself out...", inflected: "" },
    { word: "leach", part: "v.", meaning: "서서히 빼앗다, 침출되다", example: "The days blended together in a stale blur, slowly leaching the terror from her heart...", inflected: "" },
    { word: "dour", part: "adj.", meaning: "시무룩한, 뚱한, 음침한", example: "\"You always look so dour.\"", inflected: "" },
    { word: "astray", part: "adv.", meaning: "잘못된 길로, 길을 잃어", example: "\"I refuse to lead my young readers astray.\"", inflected: "" },
    { word: "brandish", part: "v.", meaning: "(무기 등을) 휘두르다", example: "...Miss Potter sang, brandishing the silver claw and circling the room.", inflected: "" }
  ]
};
