window.VOCAB_DATA = {
  title:    "Close to Famous",
  subtitle: "Ch.31 ~ Ch.35",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#4A7C59",
    bg: "#1B2E20",
    accent: "#A8D5BA",
    button: "#E4F2E8",
    buttonHover: "#D0E8D6"
  },
  words: [
    { word: "out of bounds", part: "phr.", meaning: "선을 넘은, 도를 지나친", example: "\"That's enough, Duke! You're way out of bounds.\"", inflected: "" },
    { word: "convict", part: "n.", meaning: "재소자, 복역수", example: "...you have to do this in the kitchen with an escaped convict.", inflected: "" },
    { word: "jump", part: "v.", meaning: "~을 덮치다, 습격하다 (jump + 사람)", example: "...came behind Duke like they were going to jump him.", inflected: "" },
    { word: "confectioners' sugar", part: "phr.", meaning: "슈거 파우더, 분당", example: "\"Now I'm going to add the confectioners' sugar...\"", inflected: "" },
    { word: "handcuffs", part: "n.", meaning: "수갑", example: "He put Duke in handcuffs and led him away.", inflected: "" },
    { word: "gripe", part: "v.", meaning: "투덜거리다, 불평하다", example: "People were sitting outside eating cupcakes, griping about the world.", inflected: "" },
    { word: "seal the deal", part: "phr.", meaning: "결정적으로 완성하다, 쐐기를 박다", example: "Knowing you belong is...It totally seals the deal.", inflected: "" },
    { word: "burst someone's bubble", part: "phr.", meaning: "들뜬 기대를 깨다", example: "\"Sorry, to burst your bubble, darlin'.\"", inflected: "burst your bubble" },
    { word: "specialize in", part: "phr.v.", meaning: "~을 전문으로 하다", example: "\"...a reading teacher, Mrs. Vick, who specializes in what you need.\"", inflected: "" },
    { word: "with honors", part: "phr.", meaning: "우등으로", example: "\"Foster will be receiving her reading diploma with honors.\"", inflected: "" },
    { word: "remarkable", part: "adj.", meaning: "놀라운, 주목할 만한", example: "\"...we are here to celebrate a remarkable achievement.\"", inflected: "" },
    { word: "cue", part: "n.", meaning: "(등장·행동의) 신호", example: "That was my cue to come out...", inflected: "" },
    { word: "the sky is the limit", part: "phr.", meaning: "한계가 없다, 무엇이든 가능하다", example: "\"The sky is the limit for you now.\"", inflected: "" },
    { word: "huffy", part: "adj.", meaning: "발끈한, 토라진", example: "\"Don't go getting huffy.\"", inflected: "" },
    { word: "hostile", part: "adj.", meaning: "적대적인", example: "\"You're acting downright hostile to me, girl.\"", inflected: "" },
    { word: "budge", part: "v.", meaning: "꿈쩍하다, 조금 움직이다", example: "He didn't budge, but I didn't either.", inflected: "" },
    { word: "fumble", part: "v.", meaning: "더듬거리며 찾다", example: "Huck fumbled in his wallet.", inflected: "" },
    { word: "expired", part: "adj.", meaning: "기한이 만료된", example: "\"...to begin with your license is expired.\"", inflected: "" },
    { word: "decal", part: "n.", meaning: "스티커, 전사 무늬", example: "...the old yellow Cadillac with his Elvis decal...", inflected: "" },
    { word: "press charges", part: "phr.", meaning: "고소하다, 처벌을 요구하다", example: "\"I want to press charges against the man who hit me.\"", inflected: "" },
    { word: "in custody", part: "phr.", meaning: "구금 중인", example: "\"They've got him in custody, Mrs. McFee.\"", inflected: "" },
    { word: "sole", part: "adj.", meaning: "유일한", example: "\"...an organization whose sole purpose is helping people.\"", inflected: "" },
    { word: "wail", part: "v.", meaning: "(노래를) 구성지게 뽑다, 울부짖듯 부르다", example: "She was wailing; people were nodding.", inflected: "" },
    { word: "belt out", part: "phr.v.", meaning: "(노래를) 힘껏 부르다", example: "...all the times she belted out songs in the shower...", inflected: "" },
    { word: "nodule", part: "n.", meaning: "결절 (성대의 혹)", example: "...that long year when she had nodules on her throat...", inflected: "" },
    { word: "standing ovation", part: "phr.", meaning: "기립 박수", example: "She got a standing ovation at the end.", inflected: "" },
    { word: "get a big head", part: "phr.", meaning: "우쭐해지다, 자만하다", example: "...some directors get a big head...", inflected: "" },
    { word: "glaze", part: "n.", meaning: "(설탕) 윤기 코팅", example: "All but two cupcakes came out with the pineapple sugar glaze on top.", inflected: "" },
    { word: "take a stand", part: "phr.", meaning: "입장을 분명히 밝히다, 맞서다", example: "Macon...marched up to the Culpepper Prison and took his stand.", inflected: "took his stand" },
    { word: "fall through", part: "phr.v.", meaning: "(거래가) 무산되다", example: "\"The deal fell through.\"", inflected: "fell through" },
    { word: "back out", part: "phr.v.", meaning: "(약속·거래에서) 발을 빼다", example: "\"Taco Terrific backed out.\"", inflected: "" }
  ]
};
