window.VOCAB_DATA = {
  title:    "Silent Spring",
  subtitle: "Ch.9-11",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#2E2E2E",
    bg: "#0D0D0D",
    accent: "#B0B0B0",
    button: "#F0F0F0",
    buttonHover: "#D9D9D9"
  },
  words: [
    { word: "intangible", part: "adj.", meaning: "만질 수 없는, 형체가 없는", example: "...although unseen and intangible, they are linked with the outflow of waters from the coastal rivers.", inflected: "" },
    { word: "ascend", part: "v.", meaning: "거슬러 올라가다", example: "...the salmon of the river called Miramichi... moved in from their feeding grounds in the far Atlantic and ascended their native river.", inflected: "" },
    { word: "voraciously", part: "adv.", meaning: "게걸스럽게, 왕성하게", example: "These young fed voraciously, seeking out the strange and varied insect life of the stream.", inflected: "" },
    { word: "mainstay", part: "n.", meaning: "주축, 버팀목", example: "...in an effort to save the balsams, which are the mainstay of the pulp and paper industry.", inflected: "" },
    { word: "refractory", part: "adj.", meaning: "다루기 힘든, 말을 듣지 않는", example: "The budworm populations, instead of dwindling as expected, have proved refractory...", inflected: "" },
    { word: "stopgap", part: "adj.", meaning: "임시방편의", example: "...there is no evidence anywhere that chemical spraying for budworm control is more than a stopgap measure.", inflected: "" },
    { word: "portent", part: "n.", meaning: "전조, 징후", example: "...what happened to stream fish in an area observed by the Maine Department... is perhaps a portent of things to come.", inflected: "" },
    { word: "erratically", part: "adv.", meaning: "불규칙하게, 갈피를 못 잡고", example: "...they swam erratically, gasped at the surface, and exhibited tremors and spasms.", inflected: "" },
    { word: "sluggishly", part: "adv.", meaning: "굼뜨게, 느릿느릿", example: "...the fish were moving sluggishly and made no attempt to escape.", inflected: "" },
    { word: "detritus", part: "n.", meaning: "부스러기, 유기물 찌꺼기", example: "There they remain from May or June until fall, feeding on the bottom detritus.", inflected: "" },
    { word: "misgiving", part: "n.", meaning: "불안, 의구심", example: "A good many people now have misgivings about the aerial distribution of lethal chemicals over millions of acres.", inflected: "" },
    { word: "reckless", part: "adj.", meaning: "무모한, 분별없는", example: "The gypsy moth program shows what a vast amount of damage can be done when reckless large-scale treatment is substituted for local and moderate control.", inflected: "" },
    { word: "sporadically", part: "adv.", meaning: "산발적으로", example: "It also occurs sporadically in New Jersey, where it was introduced in 1911...", inflected: "" },
    { word: "quarantine", part: "n.", meaning: "검역", example: "This natural control, plus quarantine measures and local spraying, achieved... 'outstanding restriction of distribution and damage'.", inflected: "" },
    { word: "infestation", part: "n.", meaning: "들끓음, 창궐", example: "...the 'threat of infestation of the New York City metropolitan area' has been cited as an important justification.", inflected: "" },
    { word: "injunction", part: "n.", meaning: "(법원의) 금지 명령", example: "A group of Long Island citizens... had sought a court injunction to prevent the 1957 spraying.", inflected: "" },
    { word: "inviolate", part: "adj.", meaning: "침해할 수 없는", example: "...the power and inclination of the control agencies to disregard supposedly inviolate property rights of private citizens.", inflected: "" },
    { word: "curtail", part: "v.", meaning: "축소하다, 줄이다", example: "After the disastrous 1957 spraying the program was abruptly and drastically curtailed...", inflected: "" },
    { word: "discredit", part: "v.", meaning: "신빙성을 떨어뜨리다", example: "Congressional support of the project was initially won by representations that were later discredited.", inflected: "" },
    { word: "tersely", part: "adv.", meaning: "간결하게, 짤막하게", example: "Its dismal state was tersely summarized in the spring of 1962...", inflected: "" },
    { word: "recurrent", part: "adj.", meaning: "되풀이되는", example: "Each of these recurrent exposures, no matter how slight, contributes to the progressive buildup of chemicals in our bodies.", inflected: "" },
    { word: "rudimentary", part: "adj.", meaning: "기초적인, 초보적인", example: "...provided, that is, he has even a rudimentary knowledge of the chemicals presented for his choice.", inflected: "" },
    { word: "impervious", part: "adj.", meaning: "영향을 받지 않는, 통과시키지 않는", example: "...we are presumably to infer that the human skin is impervious to chemicals.", inflected: "" },
    { word: "remiss", part: "adj.", meaning: "태만한, 소홀한", example: "Those who fail to make wide use of this array of lethal sprays and dusts are by implication remiss...", inflected: "" },
    { word: "inconspicuously", part: "adv.", meaning: "눈에 띄지 않게", example: "...warnings on labels are printed so inconspicuously in small type that few take the trouble to read or follow them.", inflected: "" },
    { word: "bewildered", part: "adj.", meaning: "어리둥절한, 갈피를 못 잡는", example: "The average purchaser is completely bewildered by the array of available insecticides, fungicides, and weed killers.", inflected: "" },
    { word: "jurisdiction", part: "n.", meaning: "관할권", example: "...it has jurisdiction only over foods shipped in interstate commerce.", inflected: "" },
    { word: "tolerance", part: "n.", meaning: "허용 기준치", example: "The system by which the Food and Drug Administration establishes maximum permissible limits of contamination, called 'tolerances', has obvious defects.", inflected: "" },
    { word: "revoke", part: "v.", meaning: "철회하다, 취소하다", example: "This happened when heptachlor was given a tolerance that later had to be revoked.", inflected: "" },
    { word: "vigilant", part: "adj.", meaning: "경계를 늦추지 않는", example: "A vigilant and aggressive Food and Drug Administration, with a greatly increased force of inspectors, is another urgent need.", inflected: "" }
  ]
};
