window.VOCAB_DATA = {
  title:    "Collective Illusions",
  subtitle: "Part III (Ch.7 The Virtue of Congruence ~ Ch.9 Living in Truth)",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#3730A3",
    bg: "#1E1B4B",
    accent: "#818CF8",
    button: "#E0E7FF",
    buttonHover: "#C7D2FE"
  },
  words: [
    { word: "infiltrate", part: "v.", meaning: "잠입하다, 침투하다", example: "in order to infiltrate the infamous Genovese, Bruno, Gambino, and DeCavalcante families", inflected: "" },
    { word: "extort", part: "v.", meaning: "갈취하다, 착취하다", example: "mob members who extorted millions from the owners of small businesses", inflected: "" },
    { word: "siphon", part: "v.", meaning: "(조금씩) 빼돌리다, 유용하다", example: "The mob was soon siphoning 25 percent of the profits from Bob's new trucking business.", inflected: "" },
    { word: "callousness", part: "n.", meaning: "냉담함, 무정함", example: "he adopted the swagger and callousness of his new companions", inflected: "" },
    { word: "erode", part: "v.", meaning: "침식하다, 서서히 무너뜨리다", example: "His former identity began to erode.", inflected: "" },
    { word: "nadir", part: "n.", meaning: "최저점, 밑바닥", example: "He hit his moral nadir one evening while riding in a car with a couple of mobsters.", inflected: "" },
    { word: "estranged", part: "adj.", meaning: "소원해진, 멀어진", example: "the more estranged he grew from Bob Delaney.", inflected: "" },
    { word: "congruence", part: "n.", meaning: "(자아와 행동의) 일치, 조화", example: "Congruence between what he believed and how he acted defined his integrity.", inflected: "" },
    { word: "cynicism", part: "n.", meaning: "냉소주의", example: "Dishonesty and cynicism are the status quo.", inflected: "" },
    { word: "dissimulate", part: "v.", meaning: "(감정·의도를) 숨기다, 위장하다", example: "his brain worked overtime to constantly dissimulate in two directions.", inflected: "" },
    { word: "hypervigilant", part: "adj.", meaning: "과잉 경계하는", example: "He became hypervigilant.", inflected: "" },
    { word: "eviscerated", part: "adj.", meaning: "(핵심이) 텅 빈, 완전히 소실된", example: "I had such an eviscerated sense of self-worth.", inflected: "" },
    { word: "paternalism", part: "n.", meaning: "온정주의, 가부장적 간섭주의", example: "the root cause of our distrust is paternalism.", inflected: "" },
    { word: "coercive", part: "adj.", meaning: "강압적인", example: "we mean that it's not just authoritative and coercive but condescending.", inflected: "" },
    { word: "condescending", part: "adj.", meaning: "거들먹거리는, 생색내는", example: "we mean that it's not just authoritative and coercive but condescending.", inflected: "" },
    { word: "benevolent", part: "adj.", meaning: "자애로운, 선의의", example: "were essentially seen as benevolent dictators.", inflected: "" },
    { word: "elitist", part: "n./adj.", meaning: "엘리트주의자(의)", example: "An elitist to his core, he used his powerful position to shape popular perceptions of industry.", inflected: "" },
    { word: "phlegmatic", part: "adj.", meaning: "냉담한, 무기력한", example: "he shall be so stupid and so phlegmatic that he more nearly resembles... the ox", inflected: "" },
    { word: "automaton", part: "n.", meaning: "자동인형, 로봇 같은 존재", example: "His transformation to an automaton is complete, but the result is disastrous.", inflected: "" },
    { word: "pervasive", part: "adj.", meaning: "만연한, 널리 퍼진", example: "Top-down Taylorism is so pervasive that we don't even notice it.", inflected: "" },
    { word: "zero-sum", part: "adj.", meaning: "제로섬의(한쪽이 얻으면 다른 쪽이 잃는)", example: "they are inclined to false zero-sum thinking.", inflected: "" },
    { word: "reciprocate", part: "v.", meaning: "보답하다, 화답하다", example: "there was no guarantee whether the unknown recipient would then reciprocate.", inflected: "" },
    { word: "recidivism", part: "n.", meaning: "재범(률)", example: "compared to the average US recidivism rate of nearly 70 percent within two years of release", inflected: "" },
    { word: "altruistic", part: "adj.", meaning: "이타적인", example: "a large majority of us like to think of ourselves as honest, moral, and altruistic.", inflected: "" },
    { word: "dissident", part: "n.", meaning: "(정치적) 반체제 인사", example: "the poet, playwright, dissident, statesman, and, later, president... Václav Havel.", inflected: "" },
    { word: "proscribe", part: "v.", meaning: "금지하다", example: "a spy-ridden Communist bureaucracy that carefully proscribed what one could say and do.", inflected: "" },
    { word: "feign", part: "v.", meaning: "~인 척하다, 가장하다", example: "everyone else feigned support for their own safety.", inflected: "" },
    { word: "farcical", part: "adj.", meaning: "우스꽝스러운, 소극 같은", example: "He stopped voting in farcical elections.", inflected: "" },
    { word: "anomaly", part: "n.", meaning: "이례적인 일, 변칙", example: "This 'Velvet Revolution'... is a true historical anomaly.", inflected: "" },
    { word: "vernacular", part: "n.", meaning: "(특정 집단의) 통용어, 일상어", example: "Quotes from it became part of that generation's vernacular.", inflected: "" },
    { word: "malnutrition", part: "n.", meaning: "영양실조", example: "confronting a terrible plague of childhood malnutrition.", inflected: "" },
    { word: "fatalism", part: "n.", meaning: "운명론, 체념", example: "she was able to encourage a shift from fatalism to curiosity.", inflected: "" },
    { word: "emboldened", part: "adj.", meaning: "대담해진, 용기를 얻은", example: "Emboldened by the community sessions... these positive deviants began to have real conversations.", inflected: "" },
    { word: "intractable", part: "adj.", meaning: "다루기 힘든, 해결하기 어려운", example: "Looking at all the massive, intractable problems in the world", inflected: "" },
    { word: "ingenuity", part: "n.", meaning: "독창성, 기발함", example: "a belief that human ingenuity is the most powerful asset of any group.", inflected: "" }
  ]
};
