window.VOCAB_DATA = {
  title:    "Horrible Histories: Woeful Second World War",
  subtitle: "Home Horrors ~ Fighting Females",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#33383D",
    bg: "#15181B",
    accent: "#7FA8C9",
    button: "#E2E5E8",
    buttonHover: "#C9CED3"
  },
  words: [
    { word: "saboteur", part: "n.", meaning: "파괴공작원, 사보타주범", example: "Bombs could blast you, saboteurs could spifflicate you and missiles marmalize you wherever you were.", inflected: "" },
    { word: "barmy", part: "adj.", meaning: "제정신이 아닌, 엉뚱한", example: "Dad's barmy army", inflected: "" },
    { word: "daft", part: "adj.", meaning: "어리석은, 얼빠진", example: "The daftest idea for uncovering a spy was to shout…", inflected: "daftest" },
    { word: "disguised", part: "adj.", meaning: "위장한, 변장한", example: "They were warned an enemy paratrooper might be disguised as a nun, a vicar or even a woman carrying a baby.", inflected: "" },
    { word: "paratrooper", part: "n.", meaning: "낙하산병", example: "They were warned an enemy paratrooper might be disguised as a nun, a vicar or even a woman carrying a baby.", inflected: "" },
    { word: "uncover", part: "v.", meaning: "(숨겨진 것을) 밝혀내다, 적발하다", example: "The daftest idea for uncovering a spy was to shout…", inflected: "" },
    { word: "chamber", part: "n.", meaning: "(총의) 약실", example: "...forgot that there was a bullet in the firing chamber.", inflected: "" },
    { word: "trigger", part: "n.", meaning: "방아쇠", example: "He pulled the trigger, the gun went off – and killed his wife.", inflected: "" },
    { word: "wounded", part: "adj.", meaning: "부상당한", example: "As he drifted down, wounded and burning, some young Home Guards began blasting at him with shotguns.", inflected: "" },
    { word: "flush out", part: "phr.v.", meaning: "(숨은 것을) 몰아내다, 색출하다", example: "You can tell that girl was keen to flush out spies!", inflected: "" },
    { word: "panicking", part: "v.", meaning: "공황 상태에 빠진", example: "An old farm worker tried to protect the inspector and was shot and killed by a panicking Home Guard member.", inflected: "" },
    { word: "harmless", part: "adj.", meaning: "무해한, 순진한", example: "The harmless old man was 68 years old.", inflected: "" },
    { word: "overheard", part: "v.", meaning: "우연히 엿들었다", example: "But the Home Guard commander (the local school teacher) overheard old Karl.", inflected: "" },
    { word: "execute", part: "v.", meaning: "처형하다", example: "He arranged to have him tried and then executed.", inflected: "" },
    { word: "hanged", part: "v.", meaning: "교수형에 처했다", example: "The old man was hanged from his own pear tree outside his own front door while his wife watched from the window.", inflected: "" },
    { word: "occupied", part: "adj.", meaning: "점령된", example: "The Germans stayed in the north and east of France and ran it as if it were Germany – it was known as 'Occupied' France.", inflected: "" },
    { word: "raided", part: "v.", meaning: "급습했다", example: "They raided homes, spied on neighbours and betrayed freedom fighters to the enemy forces.", inflected: "" },
    { word: "betrayed", part: "v.", meaning: "배신했다", example: "They had been betrayed.", inflected: "" },
    { word: "ruthless", part: "adj.", meaning: "무자비한", example: "Britain's secret army trained and dressed like Home Guard but were ruthless and tough.", inflected: "" },
    { word: "resist", part: "v.", meaning: "저항하다", example: "...secret groups began to resist German rule – they were the 'Resistance.'", inflected: "" },
    { word: "miserable", part: "adj.", meaning: "비참한", example: "The German secret police (the Gestapo) made it pretty miserable in Occupied France.", inflected: "" },
    { word: "vital", part: "adj.", meaning: "필수적인, 중대한", example: "But they did play a brave and vital part in the Resistance.", inflected: "" },
    { word: "arrested", part: "v.", meaning: "체포했다", example: "Then suddenly the Germans swooped and arrested all of SOE's agents – 1,500 of them.", inflected: "" },
    { word: "tortured", part: "v.", meaning: "고문당한", example: "Most of those brave 1,500 agents died after they'd been tortured.", inflected: "" },
    { word: "collaborator", part: "n.", meaning: "부역자, (적에게) 협력한 사람", example: "...in every one they found some local people willing to help them – 'collaborators'.", inflected: "" },
    { word: "avenge", part: "v.", meaning: "복수하다", example: "She decided to join the Resistance to avenge him.", inflected: "" },
    { word: "twisted", part: "v.", meaning: "(발목 등을) 삐었다", example: "Violette twisted a weak ankle, injured in parachute practice.", inflected: "" },
    { word: "checkpoint", part: "n.", meaning: "검문소", example: "When stopped at a German checkpoint her radio equipment was examined.", inflected: "" },
    { word: "injection", part: "n.", meaning: "주사", example: "A doctor told her he was giving her an injection to protect her against typhus.", inflected: "" },
    { word: "poison", part: "n.", meaning: "독, 독약", example: "In fact, he was injecting her with poison.", inflected: "" }
  ]
};
