window.VOCAB_DATA = {
  title:    "Alex Rider #1",
  subtitle: "Ch.12-14",
  brand:    "SueSooEnglish",
  theme: {
    primary: "#3730A3",
    bg: "#1E1B4B",
    accent: "#818CF8",
    button: "#E0E7FF",
    buttonHover: "#C7D2FE"
  },
  words: [
    { word: "seep", part: "v.", meaning: "스며들다", example: "Somehow, from somewhere, light was seeping into the area beyond the submerged tunnel.", inflected: "" },
    { word: "retreat", part: "v.", meaning: "물러나다, 후퇴하다", example: "The darkness had retreated, showing him a crossroads cut into the rock.", inflected: "" },
    { word: "sodden", part: "adj.", meaning: "흠뻑 젖은", example: "...his trainers and socks were sodden.", inflected: "" },
    { word: "squelch", part: "v.", meaning: "질척거리는 소리를 내다", example: "When he moved forward his feet squelched.", inflected: "" },
    { word: "tentatively", part: "adv.", meaning: "조심스럽게, 머뭇거리며", example: "Tentatively, Alex took hold of the grille, but it was firmly secured.", inflected: "" },
    { word: "grille", part: "n.", meaning: "쇠창살, 통풍구 덮개", example: "The light that had guided Alex was coming out of the grilles.", inflected: "" },
    { word: "decontamination", part: "n.", meaning: "오염 제거, 제독", example: "\"Red shift to assembly line. Blue shift to decontamination.\"", inflected: "" },
    { word: "conveyor-belt", part: "n.", meaning: "컨베이어 벨트", example: "The computers were being slowly carried in a long, continuous line along a conveyor-belt.", inflected: "" },
    { word: "opaque", part: "adj.", meaning: "불투명한", example: "Opaque silver test-tubes were being fed along a narrow cage.", inflected: "" },
    { word: "languidly", part: "adv.", meaning: "느릿느릿, 나른하게", example: "A lean, fair-haired figure dressed in black…walked languidly towards a door.", inflected: "" },
    { word: "sabotage", part: "v.", meaning: "파괴 공작을 하다", example: "The test-tubes were some sort of weapon that he was using to sabotage them.", inflected: "" },
    { word: "jab", part: "v.", meaning: "쿡 찌르다", example: "...something cold and solid jabbing into the back of his neck.", inflected: "jabbing" },
    { word: "ricochet", part: "v.", meaning: "튕겨 나가다, 도탄되다", example: "Bullets slammed into the wall beside him and ricocheted along the passageway.", inflected: "" },
    { word: "gantry", part: "n.", meaning: "통로 구조물, 작업용 철골 다리", example: "He was standing on a gantry leading down to a tangle of pipes and cylinders.", inflected: "" },
    { word: "inarticulate", part: "adj.", meaning: "말이 되지 않는, 알아들을 수 없는", example: "The butler made an inarticulate sound and lashed out a second time.", inflected: "" },
    { word: "livid", part: "adj.", meaning: "검붉은, 시퍼런", example: "...behind the livid scars he really was grinning.", inflected: "" },
    { word: "tendon", part: "n.", meaning: "힘줄", example: "His arms were twisted behind him and the tendons in his shoulders were on fire.", inflected: "" },
    { word: "unleash", part: "v.", meaning: "풀어놓다, 촉발시키다", example: "It was 1st April, the day when the Stormbreakers would be unleashed.", inflected: "" },
    { word: "serrated", part: "adj.", meaning: "톱니 모양의", example: "Mr Grin…took out a knife, razor sharp with a serrated edge.", inflected: "" },
    { word: "evaporate", part: "v.", meaning: "사라지다, 증발하다", example: "If there had been anything comical about him…it had completely evaporated.", inflected: "" },
    { word: "quiver", part: "v.", meaning: "떨리다, 진동하다", example: "...the knife…was suddenly quivering in the back of the chair.", inflected: "" },
    { word: "nick", part: "v.", meaning: "살짝 베다", example: "The edge of the blade had actually nicked the skin of his neck.", inflected: "" },
    { word: "smarmy", part: "adj.", meaning: "느끼하게 알랑거리는", example: "He was a small, smarmy shrimp of a boy, but his parents were rich.", inflected: "" },
    { word: "goad", part: "v.", meaning: "자극하다, 약 올리다", example: "All the time he goaded me and taunted me.", inflected: "" },
    { word: "smug", part: "adj.", meaning: "잘난 체하는, 우쭐한", example: "...the Prime Minister will make one of his smug, self-serving speeches.", inflected: "" },
    { word: "loathe", part: "v.", meaning: "몹시 싫어하다", example: "You have no idea how much I loathe you.", inflected: "" },
    { word: "recoil", part: "v.", meaning: "움찔 물러서다", example: "Alex recoiled away from her as she leaned over him.", inflected: "" },
    { word: "translucent", part: "adj.", meaning: "반투명한", example: "He could see the translucent cone, with its dark mauve tip, heading towards him.", inflected: "" },
    { word: "contort", part: "v.", meaning: "몸을 비틀다", example: "Alex contorted his body and managed to stay down.", inflected: "" },
    { word: "take stock of", part: "phr.", meaning: "~을 파악하다, 점검하다", example: "Alex burst out of the house and stopped in the open air, taking stock of his surroundings.", inflected: "" }
  ]
};
